import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StatsSection from "@/components/StatsStection";
import { Footer } from "@/components/Footer";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Google Fonts Oswald Font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white `}
      >
        <Navbar />
        {children}
        <StatsSection></StatsSection>
        <Footer></Footer>
      </body>
    </html>
  );
}
